CBTDWeb/Areas/Customer/Pages/Cart/Index.cshtml.cs
using CBTD.ApplicationCore.ViewModels;
using CBTD.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace CBTDWeb.Pages.Cart
{
    public class IndexModel : PageModel
    {

        private readonly UnitOfWork _unitOfWork;

        public ShoppingCartVM ShoppingCartVM { get; set; }
        public IndexModel(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult OnGet()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;

            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                cartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, u => u.ProductId, "Product"),

            };
            foreach (var item in ShoppingCartVM.cartItems)
            {
                item.Price = GetPriceBasedOnQuantity(item.Count, item.Product.UnitPrice,
                    item.Product.HalfDozenPrice, item.Product.DozenPrice);
                ShoppingCartVM.CartTotal += (item.Price * item.Count);
            }

            return Page();
        }

        private double GetPriceBasedOnQuantity(double quantity, double price, double priceHalfDozen, double priceDozen)
        {
            if (quantity <= 5)
            {
                return price;
            }
            else
            {
                if (quantity <= 11)
                {
                    return priceHalfDozen;
                }
                return priceDozen;
            }
        }

        public IActionResult OnPostMinus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
            if (cart.Count == 1)
            {
                _unitOfWork.ShoppingCart.Delete(cart);
            }


            else
            {
                cart.Count -= 1;


                _unitOfWork.ShoppingCart.Update(cart);
            }
            _unitOfWork.Commit();


            var cnt = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cart.ApplicationUserId).Count();
            //HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
            return RedirectToPage();




        }


        public IActionResult OnPostPlus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
            cart.Count += 1;


            _unitOfWork.ShoppingCart.Update(cart);




            _unitOfWork.Commit();




            return RedirectToPage();




        }


        public IActionResult OnPostRemove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.Get(c => c.Id == cartId);
            _unitOfWork.ShoppingCart.Delete(cart);
            _unitOfWork.Commit();
            var cnt = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cart.ApplicationUserId).Count();
            //HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
            return RedirectToPage();


        }


    }
}

CBTDWeb/Areas/Customer/Pages/Cart/OrderConfirmation.cshtml.cs
using CBTD.ApplicationCore.Models;
using CBTD.DataAccess;
using CBTD.Utility;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe.Checkout;

namespace CBTDWeb.Pages.Cart
{
    public class OrderConfirmationModel : PageModel
    {
        [BindProperty]
        public int OrderId { get; set; }
        private readonly UnitOfWork _unitOfWork;
        private readonly IEmailSender _emailSender;
        public OrderConfirmationModel(UnitOfWork unitOfWork, IEmailSender emailSender)
        {
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }
        public void OnGet(int orderId)
        {
            OrderHeader objOrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includes: "ApplicationUser");
            OrderId = objOrderHeader.Id;
            var service = new SessionService();
            Session session = service.Get(objOrderHeader.SessionId);
            //check the stripe status
            if (session.PaymentStatus.ToLower() == "paid")
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderId, SD.StatusApproved, SD.PaymentStatusApproved);
                _unitOfWork.Commit();
            }
            //Send an e-mail

            _emailSender.SendEmailAsync(objOrderHeader.ApplicationUser.Email, "New Order - CBTD", "<p>New Order Created.</p>Your order number is " + OrderId.ToString());

            //remove shopping cart items
            List<ShoppingCart> shoppingCartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId ==
            objOrderHeader.ApplicationUserId).ToList();
            _unitOfWork.ShoppingCart.Delete(shoppingCartItems);
            _unitOfWork.Commit();
        }

    }
}

CBTDWeb/Areas/Customer/Pages/Cart/Summary.cshtml.cs
using CBTD.ApplicationCore.ViewModels;
using CBTD.ApplicationCore.Models;
using CBTD.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using CBTD.Utility;
using Stripe.Checkout;

namespace CBTDWeb.Pages.Cart
{
    public class SummaryModel : PageModel
    {
        private readonly UnitOfWork _unitOfWork;

        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public SummaryModel(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }
        public IActionResult OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                cartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
                includes: "Product"),
                OrderHeader = new()
            };
            ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.Get(
                u => u.Id == claim.Value);

            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.FullName;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
            ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;

            foreach (var cart in ShoppingCartVM.cartItems)
            {
                cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.UnitPrice,
                    cart.Product.HalfDozenPrice, cart.Product.DozenPrice);
                ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;

            }
            return Page();
        }
        private double GetPriceBasedOnQuantity(int quantity, double price, double priceHalfDozen, double priceDozen)
        {
            if (quantity <= 5)
            {
                return price;
            }
            else
            {
                if (quantity <= 11)
                {
                    return priceHalfDozen;
                }
                return priceDozen;
            }
        }

		public IActionResult OnPost()
		{
			var claimsIdentity = User.Identity as ClaimsIdentity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			//The Order is actually the shopping cart items, so we might as well use it

			ShoppingCartVM.cartItems = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value,
					includes: "Product");

			ShoppingCartVM.OrderHeader.OrderDate = System.DateTime.Now;
			ShoppingCartVM.OrderHeader.ApplicationUserId = claim.Value;

			foreach (var cart in ShoppingCartVM.cartItems)
			{
				cart.Price = GetPriceBasedOnQuantity(cart.Count, cart.Product.UnitPrice,
				cart.Product.HalfDozenPrice, cart.Product.DozenPrice);
				ShoppingCartVM.OrderHeader.OrderTotal += cart.Price * cart.Count;
			}

			ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == claim.Value);

			ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
			ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusInProcess;

			_unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
			_unitOfWork.Commit();

			//Once the Order Header is created, we can start cycling through our Order Details

			foreach (var cart in ShoppingCartVM.cartItems)
			{
				OrderDetails orderDetail = new()
				{
					ProductId = cart.ProductId,
					OrderId = ShoppingCartVM.OrderHeader.Id,
					Price = cart.Price,
					Count = cart.Count
				};
				_unitOfWork.OrderDetail.Add(orderDetail);
				_unitOfWork.Commit();
			}

			//don't forget to clear the physical shopping cart entries

			_unitOfWork.ShoppingCart.Delete(ShoppingCartVM.cartItems);
			_unitOfWork.Commit();

			//stripe settings 
			var domain = "http://holo74-001-site1.atempurl.com/";
			var options = new SessionCreateOptions
			{
				PaymentMethodTypes = new List<string>
				{
				  "card",
				},
				LineItems = new List<SessionLineItemOptions>(),
				Mode = "payment",
				SuccessUrl = domain + $"cart/OrderConfirmation?Orderid={ShoppingCartVM.OrderHeader.Id}",
				CancelUrl = domain + $"cart/index",
			};

			foreach (var item in ShoppingCartVM.cartItems)
			{

				var sessionLineItem = new SessionLineItemOptions
				{
					PriceData = new SessionLineItemPriceDataOptions
					{
						UnitAmount = (long)(item.Price * 100),//20.00 -> 2000
						Currency = "usd",

						ProductData = new SessionLineItemPriceDataProductDataOptions
						{
							Name = item.Product.Name

						},

					},
					Quantity = item.Count,



				};

				options.LineItems.Add(sessionLineItem);

			}

			var service = new SessionService();
			Session session = service.Create(options);

			//grab the URL from the session
			Response.Headers.Add("Location", session.Url);
			//return a redirect to the original session location
			_unitOfWork.OrderHeader.UpdateStripePaymentID(ShoppingCartVM.OrderHeader.Id, session.Id, session.PaymentLinkId);
			_unitOfWork.Commit();

			return new StatusCodeResult(303);  //success URL

		}


	}
}

CBTDWeb/Areas/Customer/Pages/Cart/Index.cshtml
@page
@model CBTDWeb.Pages.Cart.IndexModel
@{
}
<form method="post">
    <br />
    <div class="container">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0">
                <div class="row">
                    <div class="col-6  pt-2">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Shopping Cart
                    </div>
                    <div class="col-6 text-end">
                        <a asp-page="../Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                @foreach (var item in Model.ShoppingCartVM.cartItems)
                {
                    <div class="row">
                        <div class="d-none d-lg-block col-lg-1 text-center py-2">
                            <img src="@item.Product.ImageUrl" class="rounded" style="width:100%" />
                        </div>
                        <div class="col-12 col-lg-6 pt-md-3">
                            <h5><strong>@item.Product.Name</strong></h5>
                            <p><small>@Html.Raw(item.Product.Description)</small></p>
                        </div>
                        <div class="col-12  col-lg-5 text-center row">
                            <div class="col-4 text-md-right pt-4">
                                <h6>
                                    <strong>
                                        @item.Price.ToString("c")
                                        <span class="text-muted">&nbsp;x&nbsp;</span>@item.Count
                                    </strong>
                                </h6>
                            </div>
                            <div class="col-6 col-sm-4 col-lg-6 pt-2">
                                <div class="w-75 btn-group" role="group">
                                    <button type="submit" asp-page-handler="plus" asp-route-cartId="@item.Id" class="btn btn-primary">
                                        <i class="bi bi-plus-square"></i>
                                    </button> &nbsp;
                                    <button type="submit" asp-page-handler="minus" asp-route-cartId="@item.Id" class="btn btn-warning">
                                        <i class="bi bi-dash-square"></i>
                                    </button>


                                </div>

                            </div>
                            <div class="col-2 col-sm-4 col-lg-2 text-right pt-2">
                                <button type="submit" asp-page-handler="remove" asp-route-cartId="@item.Id"  class="btn btn-danger">
                                    <i class="bi bi-trash-fill"></i>
                                </button>


                            </div>
                        </div>
                    </div>
                    <hr />
                }


                <div class="row">
                    <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between bg-light">
                                <span class="text-info"> Total (USD)</span>
                                <strong class="text-info">@Model.ShoppingCartVM.CartTotal.ToString("c")</strong>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <div class="card-footer row">
                    <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">
                        <a asp-page="summary" class="btn btn-success form-control">Summary</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

CBTDWeb/Areas/Customer/Pages/Cart/OrderConfirmation.cshtml
@page
@model CBTDWeb.Pages.Cart.OrderConfirmationModel
@{
}
<div class="container row pt-4">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Order Placed Successfully!</h1>
        Your Order Number is : @Model.OrderId <br /><br />
        <img src="~/images/OrderConfirmation.png" width="65%" />
    </div>
    <div class="col-12 text-center" style="color:maroon">
        <br />
        Your order has been placed successfully! <br />
        <a asp-page="../index">Back Home</a>
    </div>
</div>

CBTDWeb/Areas/Customer/Pages/Cart/Summary.cshtml
@page
@using Microsoft.Extensions.Options
@using CBTD.Utility
@inject IOptions<CBTD.Utility.StripeSettings> Stripe
@model CBTDWeb.Pages.Cart.SummaryModel
@{
}
<form method="post">
	<br />
	<div class="container">
		<div class="card">
			<div class="card-header bg-dark text-light ml-0">
				<div class=" row container">
					<div class="col-6">
						<i class="fa fa-shopping-cart"></i> &nbsp;
						Order Summary
					</div>
					<div class="col-6 text-end">
						<a asp-page="Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="container rounded p-2">
					<div class="row">
						<div class="col-12 col-lg-6 pb-4">
							<div class="row">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Shipping Details:</span>
								</h4>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Name</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.Name" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.Name" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Phone</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.PhoneNumber" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.PhoneNumber" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Street Address</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.StreetAddress" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.StreetAddress" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>City</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.City" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.City" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>State</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.State" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.State" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Postal Code</label>
								</div>
								<div class="col-9">
									<input asp-for="ShoppingCartVM.OrderHeader.PostalCode" class="form-control" />
									<span asp-validation-for="ShoppingCartVM.OrderHeader.PostalCode" class="text-danger"></span>
								</div>
							</div>
						</div>
						<div class="col-12 col-lg-5 offset-lg-1">
							<h4 class="d-flex justify-content-between align-items-center mb-3">
								<span class="text-info">Order Summary:</span>
							</h4>

							<ul class="list-group mb-3">
								@{
									var total = 0.0;
								}
								@foreach (var details in Model.ShoppingCartVM.cartItems)
								{
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@details.Product.Name</h6>
											<small class="text-muted">Quantity: @details.Count</small>
										</div>
										<span class="text-muted">$@((details.Price * details.Count).ToString("0.00"))</span>
										@{
											total += (details.Price * details.Count);
										}
									</li>
								}

								<li class="list-group-item d-flex justify-content-between bg-light">
									<small class="text-info">Total (USD)</small>

									<strong class="text-info">$@total.ToString("0.00")</strong>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col-12 col-md-8 pt-2">
						<p style="color:maroon; font-size:14px;">
							Estimate Arrival Date:
							@DateTime.Now.AddDays(7).ToShortDateString() - @DateTime.Now.AddDays(14).ToShortDateString()
						</p>
					</div>
					<div class="col-12 col-md-4">
						<button type="submit" value="Place Order" class="btn btn-primary form-control">Place Order</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>